### ISSUE TITLE
Print File HTML

### ISSUE THREAD

**Issue by leolyz** [qzindustries/qz-print#18]
Dear I would like to print a html file, only indicating the route, eg. ticke.html? id = 1 
As I pass the parameters?

**Comment by tresf** [comment]
@leolyz, this should work but I'm confused as to what you are trying.  Generally html wouldn't take parameters (usually php would be used for parameters).

**Comment by leolyz** [comment]
understand, to make it simpler ticket.html serious, you can tell me the function to use so the call with the button?

**Comment by tresf** [comment]
appendHTML() only supports HTML1.0.

I would recommend you use jquery $.ajax() to load the file and then html2canvas to render to image.  Due to quality reasons, I would recommend you make your html elements at least twice their size.

However, this is not the right place to ask these questions.  Please use our new Google groups here:  http://qzindustries.com/support.

-Tres
