### ISSUE TITLE
Not an issue: Just wanted to drop you a note

### ISSUE THREAD

**Issue by micwallace** [qzindustries/qz-print#48]
I've just finished the first version of this:
https://github.com/micwallace/WebPrint

I thought you might find it useful when you move qz-print away from Java Web Start.

I've also ported qz-prints escp image function into javascript and written some other escp utility stuff (function for creating a table, lots of escp command constants). I saw a request for some further escp examples, so they might be perfect.
I don't have it in a public repo at the moment but let me know if you want it and I'll send it through.

Background:
I've used qz-print in a POS system that I designed last year, which is due to be released open-source in the next few months. Being a big project, qz-print was a huge help.

Thankyou very much for your contribution to the community!

Kind regards,
Michael

**Comment by tresf** [comment]
@micwallace,

Thanks for leaving a message.  The future of qz-print will be qz-tray and it will run on the PC locally.  Our current design will maintain backwards compatibility with the exiting API (`qz.findPrinter()`, `qz.append()`, etc).

Due to the ability for any website to open a socket connection to this new version, we needed to create a secure way to communicate with the tray application.  We will be creating a signing process for this.

http://qzindustries.com/qztray

Your solution looks very useful.  If you decide to combine efforts down the road, I recommend we talk.  Please feel free to email me tres@qzindustries.com and we can talk further.

-Tres

**Comment by tresf** [comment]
We've gotten the new version with signature verification finally working.  We will offer an early download to our premium clients soon, hopefully next week.

https://qz.io/download
