### ISSUE TITLE
Printing PDF issues

### ISSUE THREAD

**Issue by mduhagon** [qzindustries/qz-print#57]
Hello, 

I am using qz print applet from a Chrome browser, to send pdf files to print from a webapp.
I can select the printer correctly, and also send a pdf file to print, but the printed result is wrong, there seems to be something wrong with the font, it's too big and stretched

If I send the same pdf to print manually to the same printer it prints out OK. 

Here I took a picture of the two, top is the wrong format, below the correct:

https://dl.dropboxusercontent.com/u/16932386/print_issues.png

The file uses Calibri as the base font, so I tried changing the font to Arial, but the result is the same.
I have no experience working with qz, maybe someone can hint what else could I try to fix the issue?

Thanks

**Comment by tresf** [comment]
QZ-Print currently ships with the 3rd-party PDF-RENDERER, which has many limitations in terms of PDF rendering.  We have a build of 1.8 built against the 3rd-party PDFBOX sources which seems to work better with some of these rendering issues, but we don't currently offer a download, you would have to build from source.

Future versions will have modular support allowing the switching of PDF renderer libraries.  Note that PDF printing currently is only supported via Java which is why the results you get from Chrome or Adobe Acrobat Viewer vary so much from the plugin.  We hope to help bridge this gap once QZ Tray is ready for a public beta.

-Tres

**Comment by tresf** [comment]
Closing as this is a problem with the 3rd party library and can only be fixed upstream by them.

That said, we have plans to integrate PDFBOX 1.8 and PDFBOX 2.0 this summer which will address many of the PDF printing problems.  Stay tuned. :)

Related:  #15
